services:
  mysql:
    image: mysql:8.0
    container_name: restaurant-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: sf_restaurant
      MYSQL_USER: restaurant_user
      MYSQL_PASSWORD: CP53goaWW8czL2N
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: restaurant-phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      # PMA_USER: restaurant_user      <- Supprime cette ligne
      # PMA_PASSWORD: CP53goaWW8czL2N  <- Supprime cette ligne
    ports:
      - "8081:80"
    depends_on:
      - mysql

volumes:
  mysql_data: